name: Publish Container Images

on:
  release:
    types:
      - published
      - edited

jobs:
  build:
    strategy:
      matrix:
        distro:
          - ubuntu-20.04
          - ubuntu-22.04
        repository:
          - actions-runner
          - actions-runner-dind
    name: Publish Container Image
    runs-on: ubuntu-20.04
    permissions:
      packages: write
    outputs:
      tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=false
          images: ghcr.io/cucxabong/${{ matrix.repository }}
          tags: |
            type=semver,pattern={{raw}},suffix=-${{ matrix.distro }}
            type=raw,value=${{ matrix.distro }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: cucxabong
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            REPOSITORY=${{ matrix.repository }}
            RUNNER_VERSION=${{ github.ref_name }}
